# Generated by Django 4.1.5 on 2023-01-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_unit_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
