# Generated by Django 4.1.5 on 2023-01-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_user_api_key_user_api_key_used_times"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20, unique=True, verbose_name="username"),
        ),
    ]
