# Generated by Django 4.1.5 on 2023-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_user_email_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="api_key_used_times",
        ),
        migrations.AddField(
            model_name="user",
            name="get_questions_count",
            field=models.IntegerField(default=0, verbose_name="get questions count"),
        ),
        migrations.AddField(
            model_name="user",
            name="max_get_questions_count",
            field=models.IntegerField(default=150, verbose_name="max get questions count"),
        ),
    ]
